// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Persistent;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241027151806_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6838e6e9-f72c-467d-8022-1e12cb3cfebc"),
                            Password = "admin",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a614ff89-c0a5-49fb-892e-a25bd0fce69f"),
                            Password = "user",
                            Role = 1,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Shoe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd4b3c6b-da25-4356-9b02-e110969eac37"),
                            Brand = "Nike",
                            Name = "Nike Air Max 90",
                            PictureUrl = "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/m55is6buar3k4isirw0k/AIR+MAX+90.png",
                            Price = 100.0,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("bea35181-46df-49b9-b072-44f0783ceb0d"),
                            Brand = "Adidas",
                            Name = "Adidas Superstar",
                            PictureUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ5aPLZv9-TuQejBdX7xycecTrxMRl4azdF_u2ts1GQmbtale2hQxq9xmp8cqZ6p5ZzOmtsCuDOodQZjHud5ZufOJIbocinSSA6Ygt7GPjCTb3OFPvvOcdMpg&usqp=CAc",
                            Price = 80.0,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("39195801-b78c-44cd-948a-008410dcff40"),
                            Brand = "Converse",
                            Name = "Converse Chuck Taylor",
                            PictureUrl = "https://product.hstatic.net/1000382698/product/162050standard_0f83705012cb41c9930c876853344a92_master.jpg",
                            Price = 60.0,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("fb2d43ea-a13d-4abb-b769-9c5e8bec6fa7"),
                            Brand = "Nike",
                            Name = "Nike Air Max 50",
                            PictureUrl = "https://kicksmaniac.com/zdjecia/2018/04/17/404/56/6867AA3824_001_4.png",
                            Price = 100.0,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("386c6eaf-3850-427e-878c-ed6f366fa4e6"),
                            Brand = "Adidas",
                            Name = "Adidas Superstar 2",
                            PictureUrl = "https://assets.adidas.com/images/w_600,f_auto,q_auto/e4a1154466e347f7a00856f0c7327afc_9366/SUPERSTAR_DJen_IH3121_01_standard.jpg",
                            Price = 80.0,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("1f86de8e-530d-4bb9-bd64-21706656fe4d"),
                            Brand = "Converse",
                            Name = "Converse Chuck TaylorSwitf",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDoUFSk5h4bCAyn-e_Pwe7C2wkBzfljFPW2g&s",
                            Price = 60.0,
                            Stock = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
